import streamlit as st
import torch
import torchvision.transforms as transforms
from torchvision import datasets
from PIL import Image
from models.resnet_model import get_model

# ----------------------------
# Page Config
# ----------------------------
st.set_page_config(
    page_title="AI Image Detector",
    page_icon="🧠",
    layout="centered"
)

st.title("🧠 AI-Generated Image Detector")
st.write("Upload an image to check whether it is Real or AI-Generated.")

# ----------------------------
# Device
# ----------------------------
device = torch.device("cpu")

# ----------------------------
# Load Model (cached)
# ----------------------------
@st.cache_resource
def load_model():
    model = get_model()
    model.load_state_dict(torch.load("best_model.pth", map_location=device))
    model.to(device)
    model.eval()
    return model

model = load_model()

# ----------------------------
# Image Transform
# ----------------------------
transform = transforms.Compose([
    transforms.Resize((128, 128)),
    transforms.ToTensor(),
    transforms.Normalize([0.5, 0.5, 0.5],
                         [0.5, 0.5, 0.5])
])

# ----------------------------
# Get True Class Mapping (Single Source of Truth)
# ----------------------------
try:
    dataset = datasets.ImageFolder(root="data/small_dataset/train")
    idx_to_class = {v: k for k, v in dataset.class_to_idx.items()}
except Exception:
    idx_to_class = {0: "fake", 1: "real"}

display_map = {
    "real": "Real",
    "fake": "AI-Generated"
}



# ----------------------------
# Upload Section
# ----------------------------
uploaded_file = st.file_uploader(
    "Choose an image...",
    type=["jpg", "jpeg", "png"]
)

if uploaded_file is not None:
    image = Image.open(uploaded_file).convert("RGB")
    st.image(image, caption="Uploaded Image", use_container_width=True)


    input_tensor = transform(image).unsqueeze(0)

    # ----------------------------
    # Prediction
    # ----------------------------
    with torch.no_grad():
        outputs = model(input_tensor)
        probabilities = torch.softmax(outputs, dim=1)
        confidence, predicted = torch.max(probabilities, 1)

    # Convert predicted index -> actual class name
    predicted_class_name = idx_to_class[predicted.item()]
    prediction = display_map.get(predicted_class_name, predicted_class_name)

    confidence_value = confidence.item() * 100

    # ----------------------------
    # Display Results
    # ----------------------------
    st.subheader(f"Prediction: {prediction}")

    st.progress(int(confidence_value))
    st.write(f"Confidence: {confidence_value:.2f}%")

    if prediction == "AI-Generated":
        st.warning("This image is likely generated by an AI model.")
    else:
        st.success("This image appears to be a real photograph.")
